# DataSource
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/EMS
    username: postgres
    password: postgres
  messages:
    basename: message/messages, message/ValidationMessages